### ISSUE TITLE
Add implementation for `/generator` (aka `/generate`) path

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#11]
We have merged first draft of the OpenAPI document for our Server API. We should implement first path and create first structure of the source code:

- create controller for `/generator` (aka `/generate`) path
- create needed services (for generator and also for archiver)
- create middlewares to validate request body (based on given operation from OpenAPI document), template's parameters, sent AsyncAPI document
- handle errors
- write tests

**Comment by BOLT04** [comment]
Hi @magicmatatjahu, PR #7 solves this issue right?

**Comment by magicmatatjahu** [comment]
@BOLT04 Yeah, it solves :)

**Comment by magicmatatjahu** [comment]
Implemented by https://github.com/asyncapi/server-api/pull/7
