### ISSUE TITLE
Add implementation for `/validate` path

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#12]
AC:
- add new path to the OpenAPI document and document it
- create controller for `/validate` path
- create needed services or reuse existing
- handle errors
- write tests

**Comment by BOLT04** [comment]
Hi @magicmatatjahu what will this endpoint implement in specific? Could you provide more details 🙂 ?

**Comment by BOLT04** [comment]
I had a look around, is this feature related to this issue https://github.com/asyncapi/studio/issues/200 ?

**Comment by magicmatatjahu** [comment]
@BOLT04 Hi! No, it's not related to the mentioned issue in the Studio. It's related to the validation of the given AsyncAPI document. In the CLI under `validate` command -> `asyncapi validate` we validate (by our parser-js package) the AsyncAPI document in input. You can see implementation [here](https://github.com/asyncapi/cli/blob/master/src/commands/validate.ts) In the line https://github.com/asyncapi/cli/blob/master/src/commands/validate.ts#L37 we exactly use the `@asyncapi/parser` package :) So as in actions:
- you should add new path to the OpenAPI spec under `/validate` path - it should be POST because we need send AsyncAPI document
- create controller for that given path
- create service. I think that `ParserService` will be good. That service should be something like "wrapper" for `@asyncapi/parser` module, only for one function `parse` from that package atm
- handle errors like in our another path `generate` -  https://github.com/asyncapi/server-api/blob/master/src/controllers/generate.controller.ts#L53
- write unit tests like https://github.com/asyncapi/server-api/blob/master/src/controllers/tests/generator.controller.test.ts

Atm we have https://github.com/asyncapi/server-api/blob/master/src/middlewares/document-validation.middleware.ts middleware which actually makes validation for the spec inside `asyncapi` field, so you should try to reuse that logic, but make from that service :) Of course, if you will have any problems please write.

@smoya Do you wanna add something?

**Comment by BOLT04** [comment]
Thank you for all the details 👍, can I start working on this or is someone already working on it?
Also, 2 other questions:
- is it okay to create a branch in this repo or should it be on a fork?
- is there a convention on branch name, like `feat/<issue-number>-<small-title>`, e.g. `feat/12-add-validate-path`

**Comment by smoya** [comment]
> is it okay to create a branch in this repo or should it be on a fork?

We do all work on individual forks, ending with the creation of a PR against the main repo.

> is there a convention on branch name, like feat/<issue-number>-<small-title>, e.g. feat/12-add-validate-path

The reality is that I didn't see a standard to be forced on this community. There is only one in terms of commits, so we all should follow [conventional commits](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md#conventional-commits). So I guess we all are free to use whatever branch naming we want. In my case, I usually use the same prefix as in conventional commits (`feat`, `docs`, `chore`...) like `<prefix>/<brief summary>`, but again I think you can follow whatever you want.

**Comment by magicmatatjahu** [comment]
As Sergio wrote, everything should be done in your fork, not in upstream repo :) Strict name of branch is not necessary, but if it helps you to manage branches in your repo, it is ok :) 

> will we have always separate controllers with one path each? Should this validate be a new controller? Initially, I thought we had a few resources, but I'm not sure resources fit this API design... or does it 🤔. I think @fmvilas mentioned using an RPC style, and the operations so far, generate and validate, seem to fit this style because it has verbs in the path (in the REST style the verbs are defined in the HTTP method). It does seem our paths are the function names, so the client of the API would call make a remote function/procedure call (RPC 😅)
What do you think @magicmatatjahu and @smoya ?

Yes, each path = separate controller. We should name every path of verb form. I know that we decided to go with resources but it doesn't work. We don't manage any db etc, but only transform AsyncAPI document and return new from that file - generated templates, validated spec, converted spec etc, so in that case verbs are move verbose :)

**Comment by smoya** [comment]
Are we gonna support both yaml and json formats? We could do it based on `Content-Type` header.

**Comment by magicmatatjahu** [comment]
We should :)
