### ISSUE TITLE
Server do not work out of the box with new `@asyncapi/specs` 4.0

### ISSUE THREAD

**Issue by derberg** [asyncapi/server-api#188]
#### Describe the bug
Tests are failing with new version -> https://github.com/asyncapi/server-api/actions/runs/3298011137/jobs/5439567189
So the bump cannot be performed -> https://github.com/asyncapi/server-api/pull/184

#### How to Reproduce
Get locally PR with bump `gh pr checkout 184` and run tests

#### Expected behavior

It should work out of the box, as in 4.0 what we did was that we just removed old specs from the package, prior 2.0

**Comment by vinibiavatti1** [comment]
I would like to work on this issue to contribute to the project. Can you assign it to me?

**Comment by BOLT04** [comment]
Sure thing, thanks @vinibiavatti1 👍
