### ISSUE TITLE
Move to the npm ci in the Dockerfile

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#36]
As in current Dockerfile we install dependencies by `npm install` due to problem described in the https://github.com/asyncapi/.github/issues/123 issue. After resolving mentioned issue we should move from `npm install` to the `npm ci`.

**Comment by abhijeetjejurkar** [comment]
Is this issue is resolved? and Remained to close?

**Comment by magicmatatjahu** [comment]
@abhijeetjejurkar Nope, we still use `npm install` https://github.com/asyncapi/server-api/blob/master/Dockerfile#L17

**Comment by BOLT04** [comment]
hi @magicmatatjahu, the PR https://github.com/asyncapi/.github/issues/123 is necessary to be merged first right?
Could we do this change with a draft PR on this repo in the meantime, wdyt?

**Comment by magicmatatjahu** [comment]
@BOLT04 Yeah, our workflow still try to install NodeJS projects with `lockVersion: 1`, so we have still problems described in the https://github.com/asyncapi/.github/issues/123 issue.

> Could we do this change with a draft PR on this repo in the meantime, wdyt?

Hmm 😅 Which PR? I don't see PR related to this problem in this repo. Could you clarify?

**Comment by BOLT04** [comment]
ohh sorry, i meant if we could open a draft PR on this repo, changing to `npm ci`. It doesn't exist yet 😅  @magicmatatjahu

**Comment by magicmatatjahu** [comment]
Aaa ok, sorry for misunderstanding! Yeah. you can create draft PR and check it :)

**Comment by smoya** [comment]
Still relevant
