### ISSUE TITLE
Add implementation for `/bundle` path

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#55]
Action points:

- add new path to the OpenAPI document and document it
- create controller for `/bundle` path
- create needed services or reuse existing
- handle errors
- write tests

Library to integrate: https://github.com/asyncapi/bundler

Before contribution please start discussion to clarify implementation and your questions/problems :)

This problem is involved in the [OpenForce event](https://github.com/asyncapi/website/pull/599). Please don't contribute if you are not participating in this event. If the problem is not solved at the end of the event, feel free to contribute :)

**Comment by Samridhi-98** [comment]
@magicmatatjahu I would like to work on this as part of OpenForce 🙂

**Comment by magicmatatjahu** [comment]
@Samridhi-98 Sure, you can. Feel free :)
