### ISSUE TITLE
Add implementation for `/diff` path

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#56]
Action points:

- add new path to the OpenAPI document and document it
- create controller for `/diff` path
- create needed services or reuse existing
- handle errors
- write tests

Library to integrate: https://github.com/asyncapi/diff

Before contribution please start discussion to clarify implementation and your questions/problems :)

This problem is involved in the [OpenForce event](https://github.com/asyncapi/website/pull/599). Please don't contribute if you are not participating in this event. If the problem is not solved at the end of the event, feel free to contribute :)

**Comment by magicmatatjahu** [comment]
@ritik307 Yeah, you could :)

**Comment by ritik307** [comment]
@magicmatatjahu I am very confused regarding the implementation 😕 can you kindly elaborate on the issue a little. 😊

**Comment by BOLT04** [comment]
Hi @ritik307 , I believe the idea is similar to the other AsyncAPI tools that are already integrated in this API.

What do you think about first designing the API contracts, a.k.a the request/response of the API endpoint? Try to think of how users of this API would like to use it, what are the use cases, etc. Then you can proceed with implementation details about this integration 🙂. 

You can also take a look at how this integration is being made on the `cli` repo here: https://github.com/asyncapi/cli/issues/58
