### ISSUE TITLE
Add `livenessProbe` and `readinessProbe` to K8s Deployment.

### ISSUE THREAD

**Issue by smoya** [asyncapi/server-api#57]
#### Reason/Context
> The [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) uses liveness probes to know when to restart a container. For example, liveness probes could catch a deadlock, where an application is running, but unable to make progress. Restarting a container in such a state can help to make the application more available despite bugs.

> The kubelet uses readiness probes to know when a container is ready to start accepting traffic. A Pod is considered ready when all of its containers are ready. One use of this signal is to control which Pods are used as backends for Services. When a Pod is not ready, it is removed from Service load balancers.

Source: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

#### Description
- Add a `livenessProbe`, with the minimum requirement of serving traffic on the HTTP port. If there is other logic that we think it makes sense to be included, we could include it as well.
- Add a `readinessProbe` with most probably the same logic as the liveness one.

**Comment by abhijeetjejurkar** [comment]
Hello sir,
Can I try to solve this issue. How can I connect you to know more about it?

**Comment by smoya** [comment]
Hi @abhijeetjejurkar! Sure, you are free to work on this.

We use Github Issues/PR's as the default communication channel. However, I invite you to join our [Slack](https://www.asyncapi.com/slack-invite) workspace, where you will find lots of folks in there (me included).

More technical details on how to proceed regarding setting K8s `livenessProbe` and `readinessProbe` can be found in K8s docs [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
In particular, our service should ensure High Availability as much as we can. The main traffic is pure HTTP.
