### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by smoya** [asyncapi/server-api#576]
Server-API is going to be migrated to be part of [CLI](https://github.com/asyncapi/cli/). See https://github.com/asyncapi/server-api/issues/485.

In the meantime, we are not accepting new PR's on this repo, not even the automated ones since a lot of work should be done regarding the Parser-JS v3 adoption, which is the main point of the Server-API to disappear in favour of CLI.

I suggest we archive this repo in two steps:

1. Click on Archive in GH, so no more new PR's or issues are accepted.
2. Once the inclusion of the Server-API into CLi happens, to move this repo into the **archive** AsyncAPI org (TSC will need to vote here).

Need your +1 if you agree, otherwise please comment @magicmatatjahu @BOLT04  

cc @derberg

**Comment by derberg** [comment]
Imho TSC voting is not needed, we do not remove project, we just move the code and functionality to another place. 

We move https://github.com/asyncapi/generator-hooks under generator and I'm also not planning to ask TSC as it is not deprecation of the project - just a location change, no?

but yeah, I guess it should not be archived until it is moved, no?

also recommend to pin this issue

**Comment by smoya** [comment]
> but yeah, I guess it should not be archived until it is moved, no?

That's the point. The reality is that I want to stop receiving new PR's, at least, those updating dependencies since CI is completely broken (and won't be fixed). That's deprecation IMHO, and I believe by deprecating this repo through GH UI first gives a cool notice so people is also aware when navigating.

I guess this should also work https://github.com/asyncapi/.github/pull/291

**Comment by derberg** [comment]
Moved to CLI: https://github.com/asyncapi/cli/issues/1790

This repo will be archived
