### ISSUE TITLE
Add Helmet to the project

### ISSUE THREAD

**Issue by BOLT04** [asyncapi/server-api#64]
#### Reason/Context
**Why do we need this improvement?**
One of the security best practices for node.js is we should [use helmet](https://expressjs.com/en/advanced/best-practice-security.html#use-helmet). This way we secure at least well-known web vulnerabilities by setting HTTP headers appropriately.

#### Description
**What changes have to be introduced?**
We should change the `app.ts` `initializeMiddlewares` function, to include the Helmet middleware.

**Comment by ritik307** [comment]
@BOLT04 I would like to work on this issue 😊

**Comment by magicmatatjahu** [comment]
@ritik307 Sure, you can work on it. Please ping us when you will have any problems :)

**Comment by BOLT04** [comment]
@ritik307 I've assigned the issue to you 🙂. Like @magicmatatjahu  said, do let us know if you have any doubts and we are happy to help 👍
