### ISSUE TITLE
Add implementation for `/optimize` path

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/server-api#80]
Action points:

- add new path to the OpenAPI document and document it
- create controller for `/optimize` path
- handle errors
- write tests

Library to integrate: https://github.com/asyncapi/optimizer

**Comment by BOLT04** [comment]
still relevant 🙂

**Comment by XshubhamX** [comment]
@BOLT04 should I start working on this.

**Comment by BOLT04** [comment]
hi @XshubhamX , sure you can work on it and submit a PR when you want 😃.
@magicmatatjahu has already worked on this issue on this PR: https://github.com/asyncapi/server-api/pull/82, you can look at it as a starting point if you want, and resume the work.

Let us know if you need anything 👍

**Comment by XshubhamX** [comment]
@BOLT04 thanks for confirming. I have also emailed you regarding some stuff related to GSOC. Can you please check?
